### ISSUE TITLE
For Newbies

### ISSUE THREAD

**Issue by Ogunthomas** [github/hubot-sans#7]
I would recommend a description be included in the installation files

**Comment by tobiasahlin** [comment]
@Ogunthomas what specifically would you like to be described in more detail? 👀

**Comment by frank-laemmer** [comment]
Before I start a new ticket with another stupid question: The README says:

> For web, we recommend using `Hubot-Sans.woff2`

I am missing where that file might be already be located or how it should build. There is a file called `HubotSans[slnt,wdth,wght].woff2` in webfonts.

**Comment by tobiasahlin** [comment]
@frank-laemmer that's a great question! The readme assumes (without stating it, so that's my fault), that the reader is referencing [the latest release](http://github.com/github/hubot-sans/releases/latest) - in that zip, there's a `Hubot-Sans.woff2` in the root folder for easy access. I'll make that more clear 👀 but that file is indeed the same as the `HubotSans[slnt,wdth,wght].woff2` file that you're referencing, so that's the one that we recommend using

**Comment by frank-laemmer** [comment]
Yes. I figured so too. So for the records. 

This is NOT working:

```css
@font-face {
  font-family: 'Hubot Sans';
  src:
    url('Hubot-Sans.woff2') format('woff2 supports variations'),
    url('Hubot-Sans.woff2') format('woff2-variations');
  font-weight: 200 900;
  font-stretch: 75% 125%;
}
```

This is working:

```css
@font-face {
  font-family: 'Hubot Sans';
  src:
    url('Hubot-Sans[slnt,wdth,wght].woff2') format('woff2 supports variations'),
    url('Hubot-Sans[slnt,wdth,wght].woff2') format('woff2-variations');
  font-weight: 200 900;
  font-stretch: 75% 125%;
}
```

for me. I'll suggest to close this.
